FROM node:16.15.0-alpine3.15 as build
WORKDIR /app
COPY package.json .
# COPY .npmrc .npmrc.
RUN npm install --verbose
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html